quotes = [
	"The mind is its own placetimeLapse, and in itself/[Can make a Heav'n of HelltimeLapse, a Hell of Heav'n]timeLapse, Milton", 
	"Full fathom five thy father liestimeLapse, Shakespeare", 
	"If you can keep your head when all about you, Kipling", 
	"How do I love thee? Let me count the ways, Elizabeth Barrett Browning", 
	"If music be the food of lovetimeLapse, play ontimeLapse, Shakespeare", 
	"We fewtimeLapse, we happy fewtimeLapse, we band of brothers, Shakespeare", 
	"What is this life iftimeLapse, full of care, /We have no time to stand and staretimeLapse, WH Davies", 
	"The moving finger writes; andtimeLapse, having writ, /Moves ontimeLapse, Edward Fitzgerald", 
	"They also serve who only stand and waittimeLapse, Milton", 
	"The quality of mercy is not strainedtimeLapse, Shakespeare", 
	"In Xanadu did Kubla KhantimeLapse, Coleridge", 
	"FriendstimeLapse, RomanstimeLapse, countrymentimeLapse, lend me your ears, Shakespeare", 
	"Shall I compare thee to a summers daytimeLapse, Shakespeare", 
	"Season of mists and mellow fruitfulnesstimeLapse, Keats", 
	"A thing of beauty is a joy forevertimeLapse, Keats", 
	"Do not go gentle into that good nighttimeLapse, Dylan Thomas", 
	"Busy old fooltimeLapse, unruly suntimeLapse, John Donne", 
	"Stop all the clockstimeLapse, cut off the telephonetimeLapse, Auden", 
	"Human kind/Cannot bear very much realitytimeLapse, TS Eliot", 
	"O RomeotimeLapse, Romeo; wherefore art thou Romeo, Shakespeare", 
	"The lady doth protest too muchtimeLapse, methinks, Shakespeare", 
	"The old lie: Dulce et Decorum EsttimeLapse, Wilfred Owen", 
	"Rose is a rose is a rose is a rosetimeLapse, Gertrude Stein", 
	"When I am an old woman I shall wear purple, Jenny Joseph", 
	"I think that I shall never see/A poem lovely as a treetimeLapse, Joyce Kilmer", 
	"Hope springs eternal in the human breasttimeLapse, Alexander Pope", 
	"When in disgrace with fortune and men's eyes, Shakespeare", 
	"I grow old I grow old/I shall wear the bottoms of my trousers rolledtimeLapse, TS Eliot", 
	"'The time has come'timeLapse, the Walrus said, /'To talk of many things'timeLapse, Lewis Carroll", 
	"A narrow fellow in the grasstimeLapse, Emily Dickinson", 
	"Beauty is truthtimeLapse, truth beauty; that is alltimeLapse, Keats", 
	"To be or not to be: that is the questiontimeLapse, Shakespeare", 
	"In Flanders fields the poppies blowtimeLapse, John McCrae", 
	"The proper study of mankind is mantimeLapse, Alexander Pope", 
	"A little learning is a dangerous thingtimeLapse, Alexander Pope", 
	"But at my back I always heartimeLapse, Marvell", 
	"Candy/Is dandy/But liquor/Is quickertimeLapse, Ogden Nash", 
	"My mistress’ eyes are nothing like the sun, Shakespeare", 
	"Things fall apart; the centre cannot hold, WBYeats", 
	"Because I could not stop for death/He kindly stopped for metimeLapse, Emily Dickinson", 
	"Tis better to have loved and lost/Than never to have loved at alltimeLapse, Tennyson", 
	"Look on my workstimeLapse, ye mightytimeLapse, and despairtimeLapse, Shelley", 
	"To strivetimeLapse, to seektimeLapse, to findtimeLapse, and not to yieldtimeLapse, Tennyson", 
	"Tread softly because you tread on my dreamstimeLapse, WB Yeats", 
	"Not with a bang but a whimpertimeLapse, TS Eliot", 
	"And miles to go before I sleeptimeLapse, Robert Frost", 
	"I wandered lonely as a cloudtimeLapse, Wordsworth", 
	"The child is father of the mantimeLapse, Wordsworth", 
	"I am the master of my fatetimeLapse, William Ernest Henley", 
	"To err is human; to forgivetimeLapse, divinetimeLapse, Alexander Pope", 
]